CREATE TABLE IF NOT EXISTS projects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  area INTEGER NOT NULL,
  rooms INTEGER NOT NULL,
  data TEXT NOT NULL,
  drawing_data TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
